repos:
   - repo: https://github.com/PyCQA/flake8
     rev: 7.1.1
     hooks:
     - id: flake8
       args: [--max-line-length=88, --extend-ignore=E203]
   - repo: https://github.com/PyCQA/bandit
     rev: 1.7.9
     hooks:
     - id: bandit
       args: [-r, --severity-level=medium, --confidence-level=medium]
